### ISSUE TITLE
Investigar sobre la conexión con GitHub

### ISSUE THREAD

**Issue by MrpYA45** [MrpYA45/github-text-mining-tfg#1]
El objetivo de esta incidencia es investigar como descargar el contenido de las issues de un repositorio mediante la API de GitHub utilizando Python.

**Comment by clopezno** [comment]
Recuerda que la guía de referencia es https://docs.github.com/en/rest/reference/issues
@Kencho ¿puedes dejar a Pablo el código de extracción de issues y almacenamiento en BD?

**Comment by Kencho** [comment]
Hola Carlos y Pablo:

Os adjunto el fragmento de código con el que hacía las descargas de
proyectos. Es un prototipo y por tanto... eso, gasolina y cerillas. Pablo,
realmente no sé si vas a poder sacar mucho de ello más allá de ver un poco
el procedimiento general (iniciar sesión, traerse datos, y esperar cuando
se alcance el límite). En particular creo que lo interesante es el
tratamiento de RateLimitExceededException (línea 63 de fetcher.py) porque
es lo único que suele impedir que se extraiga todo con un simple bucle.

Mi consejo: Trastea con github.py <https://pypi.org/project/github.py/> o
PyGithub <https://pypi.org/project/PyGithub/> en uno o dos prototipos para
ver cómo usar esos módulos para la capa de acceso a datos, cómo acceder a
la API de GitHub con ellos, en qué formato te recuperan los datos, y luego
modela la base de datos donde almacenarlos con SQLAlchemy como vimos en
clase. Después es sencillamente ir pidiendo los datos que te interesan e
insertarlos en una base de datos.

Si te surgen dudas de cómo hacer algo de esto, pregúntame.

Un saludo,

Jesús Alonso Abad

**Comment by clopezno** [comment]
Comparto el  consejo @Kencho de probar   <https://pypi.org/project/github.py/> o PyGithub <https://pypi.org/project/PyGithub/> mediante pequeños prototipos el acceso a datos.  Primero prueba con un repositorio con pocos datos y luego prueba con otro con muchos datos para ver si desde el API tienen solucionado el  _RateLimitExceededException_ con ejecuciones asíncronas. 

Para organizarte te aconsejo crear al menos 4  issues en este sprint  para los prototipos/pruebas. Documenta cada issue añadiendo el código de prueba y tiempo que tardas en obtener los datos.

**Comment by MrpYA45** [comment]
De acuerdo @clopezno y @Kencho . He estado utilizando PyGitHub y he conseguido extraer las issues con sus comentarios correctamente. Estoy haciendo las pruebas en unos notebooks hasta ver un poco como organizar el proyecto. Los dejaré en una carpeta a parte dentro del repositorio y los enlazaré con las issues.

**Comment by clopezno** [comment]
Ok. Puedes llamar a la carpeta prototipos
