### ISSUE TITLE
Cambios en README.md

### ISSUE THREAD

**Issue by alvarag** [MrpYA45/github-text-mining-tfg#43]
Buenas tardes,

Algunos cambios en el README.md sugeridos:

- Al activar el entorno virtual debe accederse al script ```env/bin/activate``` en vez de ```venv/bin/activate```
- Antes o después falta indicar que hay que entrar en la carpeta ```github-text-mining-tfg``` puesto que sino requirements no está en el directorio actual.
- En Linux puede fallar la instalación de mariadb si no se tiene el conector.

Saludos,

**Comment by MrpYA45** [comment]
Buenas tardes.

He añadido unos pequeños cambios al README.md con el objetivo de corregir y resaltar los detalles que has comentado. 
Muchas gracias por tus aportes. 

Un saludo.
