### ISSUE TITLE
Realizar el cambio de biblioteca que maneja la conexión con GitHub

### ISSUE THREAD

**Issue by MrpYA45** [MrpYA45/github-text-mining-tfg#6]
La anterior biblioteca se basaba en la versión 3 de la API de GitHub. Se pretende cambiar la biblioteca por otra que trabaje con la versión 4 de la API que utiliza GraphQL en lugar de REST. Se pretende utilizar la biblioteca [github.py](https://pypi.org/project/github.py/).

**Comment by MrpYA45** [comment]
Después de unos días de experimentación creo que sería mejor continuar utilizando la biblioteca anterior. Esto se debe a que la biblioteca de GraphQL escogida aún no dispone de la funcionalidad de recoger los comentarios de las issues como se puede apreciar [aquí](https://github.com/ShineyDev/github.py/blob/master/github/http.py#L252).
He tratado de buscar como implementarla por mi cuenta pero requiere conocer como realizar consultas mediante GraphQL. Creo que no merece la pena el esfuerzo pudiendo utilizar la biblioteca anterior, teniendo en cuenta que no se presentan indicios de que a corto plazo GitHub pretenda deshacerse de la versión REST. En caso de que en un futuro alguien desee expandir el proyecto y aparezcan alternativas más maduras sería interesante realizar mejoras en este apartado.

**Comment by clopezno** [comment]
La decisión me parece bien argumentada. Recuerda documentarla en la sección aspectos relevantes de la memoria.
